aedes:
  mq: null
  id: 'aedes-cli',
  persistence: null
  concurrency: 100
  heartbeatInterval: 60000
  connectTimeout: 30000
  keepaliveLimit: 0
  queueLimit: 42
  maxClientsIdLength: 23

secureOptions:
  cert: 'path/to/cert.pem'
  key: 'path/to/key.pem'
  rejectUnauthorized: true

servers:
  tcp:
    protocol: 'tcp'
    port: 1883

  tls:
    protocol: 'tls'
    port: 8883

  ws:
    protocol: 'ws'
    port: 3000

  wss:
    protocol: 'wss'
    port: 4000